parameters:
#    vigasin_jwt.example.class: Vigasin\JWTBundle\Example

services:
#    vigasin_jwt.example:
#        class: %vigasin_jwt.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
